# Generated by Django 4.1.2 on 2022-10-31 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_rating_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Рейтинг', 'verbose_name_plural': 'Рейтинги'},
        ),
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'verbose_name': 'Звізда рейтингу', 'verbose_name_plural': 'Звьозди рейтингу'},
        ),
    ]
